name: app_tayo_taxi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_naver_map: ^1.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.2
  http: ^1.3.0
  cloud_firestore: ^5.6.11
  intl: ^0.20.2
  url_launcher: ^6.2.5
  auto_size_text: ^3.0.0
  google_maps_flutter: ^2.5.0
  speech_to_text: ^7.2.0  # 최신 버전 확인 필요
  flutter_tts: ^4.0.2
  avatar_glow: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env