name: app_tayo_taxi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_naver_map: ^1.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.2
  http: ^1.3.0
  google_maps_flutter: ^2.5.0
  cloud_firestore: ^4.17.0
  intl: ^0.17.0
  url_launcher: ^6.2.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env